name: Build & deploy Docker images
description: Builds and deploys all Docker images

inputs:
  VERSION:
    description: 'Current GitHub tag version. if you are testing, just pass in something random like "test"'
    required: true
  SHOULD_UPLOAD:
    description: '"true" or "false"'
    required: true
    default: "true"

runs:
  using: composite
  steps:
    - name: Run script
      shell: bash
      run: bun run .github/scripts/src/build-images --ver="${{ inputs.VERSION }}" --shouldUpload "${{ inputs.SHOULD_UPLOAD }}"
