# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: CD
run-name: Running continuous deployment on ${{ github.actor }}'s commits

on:
  push:
    tags:
      - "*"

concurrency:
  group: cd
  cancel-in-progress: false

jobs:
  buildAndDeploy:
    name: Build & Deploy all Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pipeline
        uses: ./.github/composite/setup
        with:
          SECRETS: ${{ toJSON(secrets) }}

      - name: Build images
        uses: ./.github/composite/build-images
        with:
          VERSION: ${{ github.ref_name }}
          SHOULD_UPLOAD: "true"
